export enum SagaActions {
  LOGIN_USER = 'LOGIN_USER',
  LOGOUT_USER = 'LOGOUT_USER',
  ME = 'ME',
  GET_ORDERS = 'GET_ORDERS',
  GET_CATEGORIES = 'GET_CATEGORIES',
  CREATE_CATEGORY = 'CREATE_CATEGORY',
  DELETE_CATEGORY = 'DELETE_CATEGORY'
}
